
<div class="grid">
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Profile Intake Date</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" type="date" /></div><div></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Name of Child</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Date of Birth (DD/MM/YYYY)</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" placeholder="DD/MM/YYYY" /></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Sex</label><select className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all"><option></option><option>Male</option><option>Female</option><option>Other</option></select></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Address</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Previous Academic Status / School</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Father's Name (name, age etc.)</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Mother's Name</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Grandfather's Name</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Grandmother's Name</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Legal Documents of Child</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Occupation of Family</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Primary Income Source of Family</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Siblings</label><textarea placeholder="Name, age, sex and other relevant details" className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Other Relatives (Name and Relationship with the Child)</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Any Other Information Provided by Child</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Height and Weight</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Health Status</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Relationship with Family</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Contact Details</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" placeholder="Phone / Mobile / Email" /></div>
</div>
<h3 className="font-headline-sm text-headline-sm text-secondary mt-8 mb-4 border-b border-outline-variant/30 pb-2">2. Rescue / Handover Information</h3>\n<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Date of Rescue / Handover</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" type="date" /></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Circumstance of Rescue / Handover</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Organization / Place from Where Child Was Rescued From / Handed Over</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Time Spent in Organization Before Handover</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Reason Why Child Was in the Organization / Job</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">With Whom the Child Travelled to India / Work Location</label><input className="h-input-height bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all" /></div>
</div>
<h3 className="font-headline-sm text-headline-sm text-secondary mt-8 mb-4 border-b border-outline-variant/30 pb-2">3. Case Study and Assessment</h3>\n<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Case Study</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Reintegration Status</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Education</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Vocational Training</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Risk Factors</label><textarea placeholder="Child labor; other identified risks..." className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Immediate Support</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5 md:col-span-2"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Future Plan</label><textarea placeholder="Short term:\\nMedium term:\\nLong term:" className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
<div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Follow Up Plan</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div><div className="flex flex-col gap-1.5"><label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Observation by Team</label><textarea className="bg-surface px-3 py-2 rounded-lg border border-outline-variant text-on-surface font-body-md text-body-md focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary shadow-sm transition-all min-h-[105px] resize-y"></textarea></div>
</div>